### ISSUE TITLE
채팅방 항목

### ISSUE THREAD

**Issue by anemoneflower** [anemoneflower/FatOverflow#16]
- _ 시에 오세요
- _ 시에 갈게요
- _ 시에 도착한다고 합니다
- 계좌번호는 _은행 _ 입니다

**Comment by jaeyubsong** [comment]
(참가자): 돈을 보냈습니다.
(개설자): __님 돈 보내주세요.

**Comment by jaeyubsong** [comment]
(각각 얼마씩 내야 하는지 계산을 따로 해준다고 가정을 하고) => 얘는 make product page에서 제품가격 + 택배비 입력하게 해야 할듯?
__님: __원
__님: __원
...
을 보내주시기 바랍니다
